GST_STATE_CODES = {
    "01": "Jammu & Kashmir",
    "02": "Himachal Pradesh",
    "03": "Punjab",
    "04": "Chandigarh",
    "05": "Uttarakhand",
    "06": "Haryana",
    "07": "Delhi",
    "08": "Rajasthan",
    "09": "Uttar Pradesh",
    "10": "Bihar",
    "11": "Sikkim",
    "12": "Arunachal Pradesh",
    "13": "Nagaland",
    "14": "Manipur",
    "15": "Mizoram",
    "16": "Tripura",
    "17": "Meghalaya",
    "18": "Assam",
    "19": "West Bengal",
    "20": "Jharkhand",
    "21": "Odisha",
    "22": "Chhattisgarh",
    "23": "Madhya Pradesh",
    "24": "Gujarat",
    "25": "Daman & Diu and Dadra & Nagar Haveli (merged union territory)",
    "26": "Maharashtra",
    "27": "Karnataka",
    "28": "Goa",
    "29": "Lakshadweep",
    "30": "Kerala",
    "31": "Tamil Nadu",
    "32": "Puducherry",
    "33": "Andaman and Nicobar Islands",
    "34": "Telangana",
    "35": "Andhra Pradesh",
    "36": "Ladakh",
    "37": "Jharkhand",
}
