# Generated by Django 4.2.6 on 2023-10-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_ocr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceOcr',
        ),
    ]
