# Generated by Django 4.2.6 on 2023-10-14 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VendorInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(max_length=15, verbose_name='GSTIN no.')),
                ('state_code', models.CharField(max_length=5)),
                ('state_name', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('invoice_no', models.CharField(max_length=255)),
                ('po_no', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tax %')),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('result', models.BooleanField(default=True)),
                ('invoice_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.file')),
            ],
            options={
                'verbose_name': 'Vendor Invoice',
                'verbose_name_plural': 'Vendor Invoices',
            },
        ),
    ]
