# Generated by Django 4.2.6 on 2023-10-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_file_field_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
