# Generated by Django 4.2.6 on 2023-10-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_vendorinvoice_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='gstin',
            field=models.CharField(default=None, max_length=15, null=True, verbose_name='GSTIN no.'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='invoice_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='invoice_no',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='state_code',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='state_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Tax %'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='vendor_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
