# Generated by Django 4.2.6 on 2023-10-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_vendorinvoice_gstin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='tax_percent',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Tax %'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='taxable_amount',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='total_amount',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
